Add design tokens for Alert
open-formulieren/design-tokens pull request #39
Opened 2023-11-03 14:40 UTC by SilviaAmAm

Fixes open-formulieren/open-forms-sdk#467 (partly)

Still need to figure out how to get the icon color to work. Another PR will follow.

2023-11-03 14:42 UTC, SilviaAmAm commented on src/community/utrecht/alert.tokens.json
> +            "value": "#ddffdd"
We didn't have a "ok" style, so I took this colour from the backend "color success bg". Can be changed if not liked :smile:

2023-11-06 11:34 UTC, sergei-maertens requested changes

2023-11-06 11:34 UTC, sergei-maertens commented on src/community/utrecht/alert.tokens.json
> +            "value": "var(--of-color-danger)"
```suggestion
            "value": "{of.color.danger}"
```
CSS syntax is not supported in other output formats, like javascript. Instead, you need to reference it internally and the build tool will output the CSS var.

2023-11-06 11:34 UTC, sergei-maertens commented on src/community/utrecht/alert.tokens.json
> +          "end": {
the upstream design tokens are not split out that much:

https://nl-design-system.github.io/utrecht/storybook/?path=/story/css_css-alert--design-tokens

so this should be `"padding-block-end": {"value": "20px"},` instead

2023-11-06 14:07 UTC, sergei-maertens approved these changes

2023-11-06 14:07 UTC, merged